### PR TITLE
File based IO for dolt sql perf improvements

### PR DESCRIPTION
**Pull request by oscarbatori**
Including:
- let `dolt sql` write to file
- expose function parameter to parse resulting file

Goal is to expose the ability to use C path in Doltpy.

### CODE REVIEW

**Review by max-hoffman — COMMENTED** [review]
this looks like it should have two/three new tests -- file output and the json/csv parser paths

**Comment by oscarbatori** [comment]
You want to block on that? This only updates a tested codepath, so it doesn't introduce untested behavior.

**Comment by max-hoffman** [comment]
The outfile stuff looks fine, but it also doesn't look tested? I'm not gonna stop you from merging, but this is a simple process thing that when put off for too long creates all the other myriad of bugs that delay every integration.

**Comment by oscarbatori** [comment]
Yep, that's fair. I will introduce a test.

**Review by max-hoffman — APPROVED** [review]
Looks good, thanks for adding the tests

**Pull request merged**
